---
title: "Analysis of the ChickWeight dataset"
subtitle: 'MSc in Statistics 2026/27, Imperial College London, Data Science Workshop 1c'
author: "Sai Han Myo Htet"
format:
  html:
    toc: true
    highlight: tango
    self-contained: true
    df-print: paged
  pdf: default
format-links: false
bibliography: "chickWeight.bib" 
---

```{=html}
<style type="text/css">
h1{
  font-size: 24pt;
}
h2{
  font-size: 18pt;
}
body{
  font-size: 12pt;
}
</style>
```

```{r setup, include = FALSE, tidy=TRUE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
include_solutions <- TRUE
```

```{r setup2, include=FALSE, tidy=TRUE}
library(rmarkdown)
library(knitr)
library(kableExtra)
library(magrittr)
library(ggplot2)
# Put any library imports and other preamble here.
```


## Introduction

```{r echo = FALSE}

chicks <- ChickWeight
```

In this report, we perform a rudimentary analysis of the built-in ChickWeight Dataset in R. 

```{r echo = FALSE}
#| label: tbl-chicks
#| tbl-cap: "Example rows of the ChickWeight Dataset."
kable(head(chicks))
```

@tbl-chicks give example data entries from the ChickWeight dataset.


```{r echo = FALSE}
averaged_chicks <- aggregate(weight ~ Diet + Time , data = chicks, FUN = mean)

#| label: average-chicks-plot
ggplot(averaged_chicks, aes(x = Time, y = weight, color = Diet, group = Diet)) + 
  geom_point() +
  geom_line() + 
  labs(title = "Weight by time",
       caption = "Weight by time, averaged over all chicks given the same diet type")


```

```{r}
#| layout-ncol: 2
#| layout-nrow: 2


for (diet in 1:4){
  chicks_level <- chicks[chicks[,"Diet"] == diet,]
  plot(
    main = paste("Diet" , as.character(diet)),
    x = chicks_level$Time,
    y = chicks_level$weight,
    col = diet,
    pch = 14 + diet,
    type = "b",
    lty = 6,
    lwd = 1,
    bty = "n",
    ylim = c(0,450),
    xlab = "weight",
    ylab = "days after birth"
    
  )
}
```

Example citing: @wickham2017r

# Code appendix

```{r ref.label=knitr::all_labels(), echo = T, eval = F}
```

# References

:::{#refs}
